### ISSUE TITLE
Support dask-awkward inputs with weights

### ISSUE THREAD

**Issue by douglasdavis** [dask-contrib/dask-histogram#52]
Filling a histogram with dask-awkward input and including weights currently raises `NotImplementedError`, this is something we should support.

**Comment by lgray** [comment]
Just to specify - this is only for non-boost histograms. For `.boost` filling with weights is already tested against.

**Comment by douglasdavis** [comment]
Weights are supported with regular dask arrays (dataframes), but not with dask-awkward arrays. (The `.boost` module `.fill` calls use the `.core` module's `factory` function so support of any kind of object should be the same for all situations)

these are the two code blocks which need updating (it'll be a relatively trivial task to add support)

https://github.com/dask-contrib/dask-histogram/blob/8f2d8a5ddad2ea65b414f81a6b9b85b41de9a1b3/src/dask_histogram/core.py#L714-L727

https://github.com/dask-contrib/dask-histogram/blob/8f2d8a5ddad2ea65b414f81a6b9b85b41de9a1b3/src/dask_histogram/core.py#L760-L766

When I first touched this code it was really just to test that we could use the `partitionwise` graph creation tooling from dask-awkward inside of dask-histogram; I've yet to come back and add support for weights!

**Comment by lgray** [comment]
aahhh ok - didn't catch that. gotcha. thanks!
