### ISSUE TITLE
copied hist will retain the original name after computing it

### ISSUE THREAD

**Issue by iasonkrom** [dask-contrib/dask-histogram#76]
I just found out that if you change the axes name of a copied histogram, the computed histogram will retain the original axes name.
Of course I can create multiple similar histograms by copy-pasting code but I feel like this shouldn't work like that.
Here is a minimal example where I only fill it just so that it doesn't complain that the dask graph is empty when calling `compute()`.
```
import hist
import hist.dask
import dask.array as da
​
x = da.random.normal(size=100)
h1 = hist.dask.Hist(hist.axis.Regular(10, -2, 2, name="ax1"))
h2 = h1.copy()
h2.axes.name = ("ax2",)
h2.fill(x)
​
print(h2.axes.name)
print(h2.compute().axes.name)
('ax2',)
('ax1',)
```

**Comment by martindurant** [comment]
I will look in detail, but I am not immediately surprised that the "reference histogram" can be changed without changing the underlying graph of operations, which decides what you actually get from compute(). In what circumstance would you want to copy the hist object like this?

**Comment by iasonkrom** [comment]
To create similar histograms with the same axes but fill them with different things is my use case.

**Comment by martindurant** [comment]
I assume
```
h2 = hist.dask.Hist(hist.axis.Regular(10, -2, 2, name="ax2"))
```
would do the right thing, correct?

**Comment by iasonkrom** [comment]
Of course, i just submitted an issue cause I thought maybe it shouldn't work that way and maybe it can be made so that the copied hist object axis can have the "correct" name after computing.
Also it may be annoying if you have to do it many times.

**Comment by martindurant** [comment]
I expect that no thought has been put at all into how copy works :|
Probably the attributes of hist object should not be mutable at all, since (it seems) they are not reflected in the graph to be computed. I haven't dived deep enough to know if there's a simple way reflect changes into the graph.

**Comment by lgray** [comment]
@martindurant I think this can be accomplished in a not-too-painful way. I'll try my hand at it in the coming week. I need to write quite a lot of slides at this point, but I can find some time try this out. If you get to it first that's OK.
